import { useState, useRef } from 'react';
import { Scale, FileText, Upload, Loader2, AlertCircle, ArrowLeft, Shield, ShieldAlert, ShieldCheck, FileWarning, ChevronDown, ChevronUp, AlertTriangle, FileDown, RotateCcw, CheckCircle2 } from 'lucide-react';
const supabaseUrl = 'https://fbxbsslhewchyibdoyzk.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieGJzc2xoZXdjaHlpYmRveXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MzczODEsImV4cCI6MjA3ODExMzM4MX0.Z8JPlg7hhKbA624QGHp2bKKTNtCD3WInQMO5twjl6a0';
interface RiesgoContrato { clausula: string; descripcion: string; severidad: 'ALTA'|'MEDIA'|'BAJA'; sugerencia: string; }
interface AnalisisContrato { datos_extraidos: { representante_legal: string; notaria: string; numero_escritura: string; fecha_contrato: string; partes: string[]; objeto_contrato: string; vigencia: string; monto_o_tarifa: string; }; es_leonino: boolean; explicacion_leonino: string; riesgos: RiesgoContrato[]; resumen_ejecutivo: string; clausulas_faltantes: string[]; version_blindada: string; calificacion_riesgo: number; }
interface Props { onBack: () => void; }
function SectionCard({ title, icon, open, onToggle, children, bg, borderColor }: { title: string; icon: React.ReactNode; open: boolean; onToggle: () => void; children: React.ReactNode; bg?: string; borderColor?: string; }) {
  return (<div className="rounded-xl overflow-hidden" style={{ background: bg || 'rgba(255,255,255,0.03)', border: '1px solid ' + (borderColor || 'rgba(255,255,255,0.08)') }}><button onClick={onToggle} className="w-full flex items-center justify-between p-5 hover:bg-white/5 transition-colors"><div className="flex items-center gap-3">{icon}<span style={{ fontFamily: "'Exo 2', sans-serif", fontSize: '16px', fontWeight: 600, color: '#fff' }}>{title}</span></div>{open ? <ChevronUp className="w-5 h-5 text-white/40" /> : <ChevronDown className="w-5 h-5 text-white/40" />}</button>{open && <div className="px-5 pb-5">{children}</div>}</div>);
}
export default function AnalisisContratosModule({ onBack }: Props) {
  const [archivoContrato, setArchivoContrato] = useState<File | null>(null);
  const [archivoBase64, setArchivoBase64] = useState('');
  const [analizando, setAnalizando] = useState(false);
  const [resultado, setResultado] = useState<AnalisisContrato | null>(null);
  const [error, setError] = useState('');
  const [secciones, setSecciones] = useState<Record<string, boolean>>({ datos: true, leonino: true, riesgos: true, faltantes: true, resumen: true, blindado: false });
  const [dragOver, setDragOver] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const handleFile = (file: File) => { if (!file) return; if (file.size > 25*1024*1024) { setError('Max 25MB'); return; } setArchivoContrato(file); setError(''); setResultado(null); const r = new FileReader(); r.onload = () => setArchivoBase64((r.result as string).split(',')[1]); r.readAsDataURL(file); };
  const analizar = async () => { if (!archivoBase64 || !archivoContrato) return; setAnalizando(true); setError(''); setResultado(null); try { const res = await fetch(supabaseUrl+'/functions/v1/analizar-contrato', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer '+supabaseAnonKey }, body: JSON.stringify({ archivo_base64: archivoBase64, nombre_archivo: archivoContrato.name, tipo_archivo: archivoContrato.type || 'application/pdf', fecha_analisis: new Date().toLocaleDateString('es-MX', { day: '2-digit', month: 'long', year: 'numeric' }) }) }); const data = await res.json(); if (data.success && data.analisis) setResultado(data.analisis); else setError(data.error || 'Error al analizar'); } catch { setError('Error de conexion'); } finally { setAnalizando(false); } };
  const reset = () => { setArchivoContrato(null); setArchivoBase64(''); setResultado(null); setError(''); };
  const toggle = (s: string) => setSecciones(p => ({ ...p, [s]: !p[s] }));
  const sevColor = (s: string) => s === 'ALTA' ? { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.4)', text: '#fca5a5' } : s === 'MEDIA' ? { bg: 'rgba(245,158,11,0.15)', border: 'rgba(245,158,11,0.4)', text: '#fcd34d' } : { bg: 'rgba(59,130,246,0.15)', border: 'rgba(59,130,246,0.4)', text: '#93c5fd' };
  const riskColor = (n: number) => n <= 3 ? { color: '#22c55e', label: 'BAJO', bg: 'rgba(34,197,94,0.15)' } : n <= 6 ? { color: '#f59e0b', label: 'MEDIO', bg: 'rgba(245,158,11,0.15)' } : { color: '#ef4444', label: 'ALTO', bg: 'rgba(239,68,68,0.15)' };
  const descargar = () => { if (!resultado) return; const r = resultado; let c = 'ANALISIS DE CONTRATO - GRUPO LOMA | TROB\n'; c += 'Fecha: '+new Date().toLocaleDateString('es-MX')+'\nArchivo: '+(archivoContrato?.name||'')+'\nRiesgo: '+r.calificacion_riesgo+'/10\n\n'; c += 'DATOS\nRep Legal: '+r.datos_extraidos.representante_legal+'\nNotaria: '+r.datos_extraidos.notaria+'\nEscritura: '+r.datos_extraidos.numero_escritura+'\nFecha: '+r.datos_extraidos.fecha_contrato+'\nPartes: '+r.datos_extraidos.partes.join(' | ')+'\nObjeto: '+r.datos_extraidos.objeto_contrato+'\nVigencia: '+r.datos_extraidos.vigencia+'\nMonto: '+r.datos_extraidos.monto_o_tarifa+'\n\n'; c += 'LEONINO: '+(r.es_leonino?'SI':'NO')+'\n'+r.explicacion_leonino+'\n\nRIESGOS\n'; r.riesgos.forEach((ri,i) => { c += (i+1)+'. ['+ri.severidad+'] '+ri.clausula+'\n   '+ri.descripcion+'\n   Sug: '+ri.sugerencia+'\n\n'; }); if (r.clausulas_faltantes.length) { c += 'FALTANTES\n'; r.clausulas_faltantes.forEach((cl,i) => { c += (i+1)+'. '+cl+'\n'; }); } c += '\nRESUMEN\n'+r.resumen_ejecutivo+'\n\nBLINDADA\n'+r.version_blindada+'\n\nFX27 - '+new Date().toLocaleString('es-MX'); const blob = new Blob([c], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'Analisis_contrato_'+new Date().toISOString().split('T')[0]+'.txt'; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url); };
  const F = "'Exo 2', sans-serif";
  return (
    <div className="relative w-full min-h-screen overflow-auto">
      <div className="fixed inset-0" style={{ background: 'linear-gradient(135deg, #001f4d 0%, #003d7a 25%, #0066cc 50%, #1a8fff 75%, #4da6ff 100%)', zIndex: 0 }} />
      <div className="fixed inset-0" style={{ background: 'linear-gradient(180deg, rgba(0,0,0,0.25) 0%, rgba(0,0,0,0.15) 50%, rgba(0,0,0,0.25) 100%)', zIndex: 0 }} />
      <div className="sticky top-0 z-40" style={{ height: '80px', background: 'linear-gradient(180deg, rgba(15,25,45,0.92) 0%, rgba(10,18,32,0.75) 100%)', backdropFilter: 'blur(20px)', borderBottom: '1px solid rgba(80,120,180,0.15)' }}>
        <div className="h-full flex items-center justify-between px-8">
          <button onClick={onBack} style={{ background: '#fe5000', borderRadius: '8px', width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center', border: 'none', cursor: 'pointer' }}><ArrowLeft style={{ width: '20px', height: '20px', color: '#fff' }} /></button>
          <span style={{ fontFamily: F, fontSize: '20px', fontWeight: 600, color: '#fff', position: 'absolute', left: '50%', transform: 'translateX(-50%)' }}>Analisis de Contratos</span>
          <img src="/fx27-logo.png" alt="FX27" style={{ height: '45px' }} onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }} />
        </div>
      </div>
      <div className="relative z-10 p-8 max-w-5xl mx-auto">
        <div className="flex items-center gap-4 mb-8"><div className="p-3 rounded-xl" style={{ background: 'rgba(139,92,246,0.2)' }}><Scale className="w-8 h-8" style={{ color: '#a78bfa' }} /></div><div><h3 style={{ fontFamily: F, fontSize: '22px', fontWeight: 600, color: '#fff' }}>Analisis de Contratos con IA</h3><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.5)' }}>Detecta clausulas leoninas, riesgos y genera version blindada para TROB</p></div></div>
        {!resultado && (
          <div className="rounded-xl p-8" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <div className="rounded-xl p-12 text-center cursor-pointer transition-all" style={{ background: dragOver ? 'rgba(139,92,246,0.1)' : 'rgba(255,255,255,0.02)', border: '2px dashed '+(dragOver ? 'rgba(139,92,246,0.6)' : archivoContrato ? 'rgba(34,197,94,0.4)' : 'rgba(255,255,255,0.15)') }} onDragOver={(e) => { e.preventDefault(); setDragOver(true); }} onDragLeave={() => setDragOver(false)} onDrop={(e) => { e.preventDefault(); setDragOver(false); if (e.dataTransfer.files[0]) handleFile(e.dataTransfer.files[0]); }} onClick={() => fileRef.current?.click()}>
              <input ref={fileRef} type="file" accept=".pdf,.doc,.docx,.xlsx,.xls,.csv,.png,.jpg,.jpeg" className="hidden" onChange={(e) => { if (e.target.files?.[0]) handleFile(e.target.files[0]); }} />
              {archivoContrato ? (<div className="flex flex-col items-center gap-4"><div className="p-4 rounded-full" style={{ background: 'rgba(34,197,94,0.15)' }}><FileText className="w-12 h-12" style={{ color: '#22c55e' }} /></div><p style={{ fontFamily: F, fontSize: '16px', fontWeight: 600, color: '#fff' }}>{archivoContrato.name}</p><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.5)' }}>{(archivoContrato.size/1024/1024).toFixed(2)} MB</p><button onClick={(e) => { e.stopPropagation(); reset(); }} className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-white/10" style={{ border: '1px solid rgba(255,255,255,0.15)' }}><RotateCcw className="w-4 h-4 text-white/60" /><span style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.6)' }}>Cambiar</span></button></div>) : (<div className="flex flex-col items-center gap-4"><div className="p-4 rounded-full" style={{ background: 'rgba(139,92,246,0.1)' }}><Upload className="w-12 h-12" style={{ color: 'rgba(255,255,255,0.4)' }} /></div><p style={{ fontFamily: F, fontSize: '16px', fontWeight: 500, color: 'rgba(255,255,255,0.8)' }}>Arrastra el contrato o haz clic</p><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.4)' }}>PDF, Word, Imagenes - Max 25MB</p></div>)}
            </div>
            {error && <div className="mt-4 p-4 rounded-lg flex items-center gap-3" style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.3)' }}><AlertCircle className="w-5 h-5" style={{ color: '#ef4444' }} /><span style={{ fontFamily: F, fontSize: '14px', color: '#fca5a5' }}>{error}</span></div>}
            <button onClick={analizar} disabled={!archivoContrato || analizando} className="w-full mt-6 flex items-center justify-center gap-3 py-4 rounded-lg transition-all disabled:opacity-40" style={{ background: archivoContrato ? 'linear-gradient(135deg, #7c3aed, #5b21b6)' : 'rgba(255,255,255,0.05)', fontFamily: F, fontSize: '15px', fontWeight: 600, color: '#fff' }}>{analizando ? <><Loader2 className="w-5 h-5 animate-spin" /> Analizando... 30-60 seg</> : <><Scale className="w-5 h-5" /> Analizar Contrato</>}</button>
            {analizando && <div className="mt-6 space-y-3">{['Extrayendo texto...','Identificando partes...','Analizando clausulas...','Evaluando riesgos...','Generando blindada...'].map((p,i) => <div key={i} className="flex items-center gap-3 animate-pulse" style={{ animationDelay: i*0.3+'s' }}><div className="w-2 h-2 rounded-full" style={{ background: '#a78bfa' }} /><span style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.5)' }}>{p}</span></div>)}</div>}
          </div>
        )}
        {resultado && (
          <div className="space-y-4">
            {(() => { const rg = riskColor(resultado.calificacion_riesgo); return (<div className="rounded-xl p-6 flex items-center justify-between flex-wrap gap-4" style={{ background: rg.bg, border: '1px solid '+rg.color+'40' }}><div className="flex items-center gap-4">{resultado.calificacion_riesgo > 6 ? <ShieldAlert className="w-10 h-10" style={{ color: rg.color }} /> : resultado.calificacion_riesgo > 3 ? <Shield className="w-10 h-10" style={{ color: rg.color }} /> : <ShieldCheck className="w-10 h-10" style={{ color: rg.color }} />}<div><p style={{ fontFamily: F, fontSize: '18px', fontWeight: 700, color: rg.color }}>RIESGO {rg.label} - {resultado.calificacion_riesgo}/10</p><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.6)' }}>{resultado.riesgos.length} riesgos{resultado.es_leonino && ' - LEONINO'}</p></div></div><div className="flex gap-3"><button onClick={descargar} className="flex items-center gap-2 px-5 py-3 rounded-lg hover:brightness-110" style={{ background: 'linear-gradient(135deg, #fe5000, #cc4000)', fontFamily: F, fontSize: '14px', fontWeight: 600, color: '#fff' }}><FileDown className="w-5 h-5" /> Descargar</button><button onClick={reset} className="flex items-center gap-2 px-4 py-3 rounded-lg hover:bg-white/10" style={{ border: '1px solid rgba(255,255,255,0.2)', fontFamily: F, fontSize: '14px', color: 'rgba(255,255,255,0.7)' }}><RotateCcw className="w-4 h-4" /> Nuevo</button></div></div>); })()}
            <SectionCard title="Datos Extraidos" icon={<FileText className="w-5 h-5" style={{ color: '#a78bfa' }} />} open={secciones.datos} onToggle={() => toggle('datos')}><div className="grid grid-cols-2 gap-4">{[{l:'Rep. Legal',v:resultado.datos_extraidos.representante_legal},{l:'Notaria',v:resultado.datos_extraidos.notaria},{l:'Escritura',v:resultado.datos_extraidos.numero_escritura},{l:'Fecha',v:resultado.datos_extraidos.fecha_contrato},{l:'Objeto',v:resultado.datos_extraidos.objeto_contrato},{l:'Vigencia',v:resultado.datos_extraidos.vigencia},{l:'Monto',v:resultado.datos_extraidos.monto_o_tarifa}].map(c => <div key={c.l} className="p-3 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}><p style={{ fontFamily: F, fontSize: '11px', fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase' }}>{c.l}</p><p style={{ fontFamily: F, fontSize: '14px', color: '#fff', marginTop: '4px' }}>{c.v || 'N/A'}</p></div>)}<div className="col-span-2 p-3 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}><p style={{ fontFamily: F, fontSize: '11px', fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase' }}>Partes</p><p style={{ fontFamily: F, fontSize: '14px', color: '#fff', marginTop: '4px' }}>{resultado.datos_extraidos.partes.join(' - ')}</p></div></div></SectionCard>
            <SectionCard title={'Leonino - '+(resultado.es_leonino ? 'DETECTADO' : 'NO')} icon={resultado.es_leonino ? <AlertTriangle className="w-5 h-5" style={{ color: '#ef4444' }} /> : <ShieldCheck className="w-5 h-5" style={{ color: '#22c55e' }} />} open={secciones.leonino} onToggle={() => toggle('leonino')} bg={resultado.es_leonino ? 'rgba(239,68,68,0.05)' : 'rgba(34,197,94,0.05)'} borderColor={resultado.es_leonino ? 'rgba(239,68,68,0.2)' : 'rgba(34,197,94,0.2)'}><p style={{ fontFamily: F, fontSize: '14px', color: 'rgba(255,255,255,0.8)', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>{resultado.explicacion_leonino}</p></SectionCard>
            <SectionCard title={'Riesgos ('+resultado.riesgos.length+')'} icon={<FileWarning className="w-5 h-5" style={{ color: '#f59e0b' }} />} open={secciones.riesgos} onToggle={() => toggle('riesgos')}><div className="space-y-3">{resultado.riesgos.map((r,i) => { const c = sevColor(r.severidad); return (<div key={i} className="rounded-lg p-4" style={{ background: c.bg, border: '1px solid '+c.border }}><div className="flex items-start justify-between mb-2"><p style={{ fontFamily: F, fontSize: '15px', fontWeight: 600, color: '#fff' }}>{r.clausula}</p><span className="px-3 py-1 rounded-full text-xs font-bold" style={{ background: c.bg, color: c.text, border: '1px solid '+c.border }}>{r.severidad}</span></div><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.7)', marginBottom: '8px' }}>{r.descripcion}</p><div className="flex items-start gap-2 p-3 rounded-lg" style={{ background: 'rgba(34,197,94,0.1)', border: '1px solid rgba(34,197,94,0.2)' }}><ShieldCheck className="w-4 h-4 mt-0.5" style={{ color: '#22c55e' }} /><p style={{ fontFamily: F, fontSize: '12px', color: '#86efac' }}><strong>Sugerencia:</strong> {r.sugerencia}</p></div></div>); })}</div></SectionCard>
            {resultado.clausulas_faltantes.length > 0 && <SectionCard title={'Faltantes ('+resultado.clausulas_faltantes.length+')'} icon={<AlertTriangle className="w-5 h-5" style={{ color: '#f59e0b' }} />} open={secciones.faltantes} onToggle={() => toggle('faltantes')} bg="rgba(245,158,11,0.05)" borderColor="rgba(245,158,11,0.2)"><div className="space-y-2">{resultado.clausulas_faltantes.map((cl,i) => <div key={i} className="flex items-start gap-3 p-3 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}><span style={{ fontFamily: F, fontSize: '13px', fontWeight: 700, color: '#f59e0b' }}>{i+1}.</span><p style={{ fontFamily: F, fontSize: '13px', color: 'rgba(255,255,255,0.8)' }}>{cl}</p></div>)}</div></SectionCard>}
            <SectionCard title="Resumen Ejecutivo" icon={<FileText className="w-5 h-5" style={{ color: '#3b82f6' }} />} open={secciones.resumen} onToggle={() => toggle('resumen')} bg="rgba(59,130,246,0.05)" borderColor="rgba(59,130,246,0.2)"><p style={{ fontFamily: F, fontSize: '14px', color: 'rgba(255,255,255,0.8)', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>{resultado.resumen_ejecutivo}</p></SectionCard>
            <SectionCard title="Version Blindada para TROB" icon={<ShieldCheck className="w-5 h-5" style={{ color: '#22c55e' }} />} open={secciones.blindado} onToggle={() => toggle('blindado')} bg="rgba(34,197,94,0.05)" borderColor="rgba(34,197,94,0.2)"><p style={{ fontFamily: F, fontSize: '14px', color: 'rgba(255,255,255,0.8)', lineHeight: '1.7', whiteSpace: 'pre-wrap' }}>{resultado.version_blindada}</p></SectionCard>
            <div className="flex justify-center pt-4 pb-8"><button onClick={descargar} className="flex items-center gap-3 px-8 py-4 rounded-xl hover:brightness-110" style={{ background: 'linear-gradient(135deg, #fe5000, #cc4000)', fontFamily: F, fontSize: '16px', fontWeight: 600, color: '#fff', boxShadow: '0 4px 15px rgba(254,80,0,0.3)' }}><FileDown className="w-6 h-6" /> Descargar Analisis Completo</button></div>
          </div>
        )}
      </div>
    </div>
  );
}
